server {
    listen 80;
    
    # Standardowy katalog Nginxa - tu wrzucimy pliki w Dockerfile
    root /usr/share/nginx/html;
    index index.html;

    # Obsługa typów plików (żeby JS był JS-em)
    include /etc/nginx/mime.types;

    # Routing SPA (React)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache dla plików statycznych (opcjonalnie)
    location ~* \.(?:css|js|jpg|svg|ico)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}